# ===== INSTALL =====
# `npm i -g pyright`
# `pip install -U black pylint`
# ===== HOW TO USE =====
# `black *.py`
# `pyright *.py`
# `pylint *.py`



# code formatter
[tool.black]
experimental-string-processing = true
skip-string-normalization = true

line-length = 95 # Also remember to change this in [pylint]

workers = 4
fast = true
